plugins:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.4
  NewCops: disable

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
