AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
