# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36b1ecf388ac49dcfeda60982281fc69b4cb36fc996799a2ffcdca6023986aa1db1f66226ab25bfe03e5cc97acaebe8c17db4ccc00babf30123d956578edd1e3

test:
  secret_key_base: 0b6ad7fe248ed9a7402728a00cc31103043f1b991f318c0336a3ff8c549578a70cd685fd52ca01e174079f2adb6ebad5c890672331c994901b8f47f207e930a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
